export const GLOBAL_DATABASE_CONNECTION = "GLOBAL_DATABASE_CONNECTION";
export const GLOBAL_DATABASE_POOL = "GLOBAL_DATABASE_POOL";
export const LOCAL_DATABASE_CONNECTION = "LOCAL_DATABASE_CONNECTION";
