/**
 * Migration Journal Service
 *
 * Reads the Drizzle-generated `meta/_journal.json` file to determine what
 * migrations exist in the current code. Serves as the single source of truth
 * for registration guard checks — no hand-maintained manifest needed.
 *
 * The `_journal.json` is auto-generated by `drizzle-kit generate` and tracks
 * every migration with its index, tag (filename), and breakpoints.
 *
 * Structure of _journal.json:
 * {
 *   "version": "7",
 *   "dialect": "postgresql",
 *   "entries": [
 *     { "idx": 0, "version": "7", "when": 123456, "tag": "0000_initial", "breakpoints": true },
 *     ...
 *   ]
 * }
 */

import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { Injectable, Logger } from "@nestjs/common";

// Resolve path relative to this file
// This file lives at: apps/api/src/core/utils/migration-journal.service.ts
// Target:          apps/api/src/config/drizzle/global/migrations/meta/_journal.json
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const JOURNAL_PATH = join(
  __dirname, "..", "..", "..",
  "src", "config", "drizzle", "global", "migrations", "meta", "_journal.json",
);

// ─── Types ────────────────────────────────────────────────────────────────────

export interface JournalEntry {
  idx: number;
  version: string;
  when: number;
  tag: string;
  breakpoints: boolean;
}

export interface MigrationJournal {
  version: string;
  dialect: string;
  entries: JournalEntry[];
}

// ─── Service ──────────────────────────────────────────────────────────────────

@Injectable()
export class MigrationJournalService {
  private readonly logger = new Logger(MigrationJournalService.name);
  private journal: MigrationJournal | null = null;

  /**
   * Load the journal from disk. Results are cached after first read.
   */
  load(): MigrationJournal {
    if (this.journal) return this.journal;

    try {
      const raw = readFileSync(JOURNAL_PATH, "utf-8");
      const parsed = JSON.parse(raw) as MigrationJournal;

      if (!parsed.entries || !Array.isArray(parsed.entries)) {
        throw new Error("Journal has no entries array");
      }

      // Validate entries have required fields
      for (const entry of parsed.entries) {
        if (typeof entry.idx !== "number" || typeof entry.tag !== "string") {
          throw new Error(
            `Invalid journal entry at idx ${entry.idx}: missing idx or tag`,
          );
        }
      }

      this.journal = parsed;
      this.logger.log(
        `📖 Loaded migration journal: ${parsed.entries.length} migration(s), schema version ${parsed.version}`,
      );
      return parsed;
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      this.logger.error(`❌ Failed to load migration journal: ${message}`);
      throw new Error(
        `Migration journal missing or corrupted at ${JOURNAL_PATH}: ${message}`,
      );
    }
  }

  /**
   * Get the list of all migration tags from the journal.
   * Tags are like "0000_brave_steve_rogers", "0011_cynical_goliath", etc.
   */
  getMigrationTags(): string[] {
    return this.load().entries.map((e) => e.tag);
  }

  /**
   * Get the latest migration tag (the highest idx).
   */
  getLatestMigrationTag(): string | null {
    const entries = this.load().entries;
    if (entries.length === 0) return null;
    const sorted = [...entries].sort((a, b) => b.idx - a.idx);
    return sorted[0]!.tag;
  }

  /**
   * Get the latest migration index.
   */
  getLatestMigrationIdx(): number {
    const entries = this.load().entries;
    if (entries.length === 0) return -1;
    return Math.max(...entries.map((e) => e.idx));
  }

  /**
   * Check if a specific migration tag exists in the journal.
   */
  hasMigration(tag: string): boolean {
    return this.load().entries.some((e) => e.tag === tag);
  }

  /**
   * Count how many migrations exist in the journal.
   */
  getMigrationCount(): number {
    return this.load().entries.length;
  }
}
