-- 0023_talented_carmella_unuscione.sql
-- Evolve the project_role enum from ('owner','admin','developer','viewer')
-- to ('owner','maintainer','deployer','viewer').
--
-- NOTE: This migration was originally generated by Drizzle and contained many
-- statements that duplicated earlier migrations (0016/0017/0018/0020/0021/0022
-- already created the service_*/environment_kind enums, service_environments,
-- gitlab_apps, the services enum conversions, and the environments/projects/
-- services columns). Those duplicates made a fresh setup fail with
-- "type ... already exists" / "relation ... already exists". Only the
-- project_role evolution below is unique to this migration.
ALTER TABLE "project_collaborators" ALTER COLUMN "role" SET DATA TYPE text USING "role"::text;--> statement-breakpoint
ALTER TABLE "project_collaborators" ALTER COLUMN "role" SET DEFAULT 'viewer'::text;--> statement-breakpoint
DROP TYPE "public"."project_role";--> statement-breakpoint
CREATE TYPE "public"."project_role" AS ENUM('owner', 'maintainer', 'deployer', 'viewer');--> statement-breakpoint
ALTER TABLE "project_collaborators" ALTER COLUMN "role" SET DEFAULT 'viewer'::"public"."project_role";--> statement-breakpoint
ALTER TABLE "project_collaborators" ALTER COLUMN "role" SET DATA TYPE "public"."project_role" USING "role"::"public"."project_role";--> statement-breakpoint